server:
  port: 9090

spring:
  application:
    name: customer-registration
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/microservico_cliente?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: password
